version = 0.1
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::135808949659:user/aws-sam-cli-managed-dev-pipeline-resou-PipelineUser-oNlIzDJXe0Jb"
permissions_provider = "AWS IAM"

[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::135808949659:role/aws-sam-cli-managed-dev-pipel-PipelineExecutionRole-IA7Ho0ZWslW0"
cloudformation_execution_role = "arn:aws:iam::135808949659:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionRo-L4HqaRohLr6P"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-r-artifactsbucket-ce0mwvfgiqlu"
image_repository = ""
region = "ap-south-1"

[prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::135808949659:role/aws-sam-cli-managed-prod-pipe-PipelineExecutionRole-yGJdXnqpuGyU"
cloudformation_execution_role = "arn:aws:iam::135808949659:role/aws-sam-cli-managed-prod--CloudFormationExecutionRo-MsyzdKUr6y2Z"
artifacts_bucket = "aws-sam-cli-managed-prod-pipeline--artifactsbucket-mcfyiejqhqog"
image_repository = ""
region = "ap-south-1"
