branch-defaults:
  main:
    environment: student-env
    group_suffix: null

global:
  application_name: student-app
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.8
  default_region: ap-south-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  repository: null
  sc: git
  workspace_type: Application
