AWSTemplateFormatVersion: '2010-09-01'
Description: Pipeline execution role for SAM deployments

Resources:
  PipelineExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: aws-sam-cli-managed-dev-pipel-PipelineExecutionRole-IA7Ho0ZWslW0
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudformation.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSCloudFormationFullAccess
      Policies:
        - PolicyName: SAMPipelineExecutionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:CreateBucket
                  - s3:DeleteBucket
                  - s3:PutBucketPolicy
                  - s3:GetBucketPolicy
                  - s3:HeadBucket
                  - s3:PutObject
                  - s3:GetObject
                  - s3:DeleteObject
                  - s3:ListBucket
                Resource: 
                  - arn:aws:s3:::testingcrud
                  - arn:aws:s3:::testingcrud/*
