name: Deploy Student CRUD App

on:
  push:
    branches:
      - main  # Runs on every push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      - name: Install Dependencies
        run: pip install -r backend/lambda_functions/requirements.txt

      - name: Install EB CLI
        run: |
          pip install awsebcli
          pip install awscli

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Zip Lambda Functions
        run: |
          cd backend/lambda_functions
          zip -r ../../lambda.zip .
          cd ../../
          ls -lh  # List files to verify zip

      - name: Deploy Lambda Functions
        env:
          LAMBDA_FUNCTION_ADD: ${{ secrets.LAMBDA_FUNCTION_ADD }}
          LAMBDA_FUNCTION_GET: ${{ secrets.LAMBDA_FUNCTION_GET }}
          LAMBDA_EXECUTION_ROLE: arn:aws:iam::135808949659:role/LambdaExecutionRole
        run: |
          for function in $LAMBDA_FUNCTION_ADD $LAMBDA_FUNCTION_GET; do
            if aws lambda get-function --function-name $function; then
              echo "Updating existing function $function"
              aws lambda update-function-code --function-name $function --zip-file fileb://lambda.zip
            else
              echo "Creating new function $function"
              aws lambda create-function \
                --function-name $function \
                --runtime python3.8 \
                --role $LAMBDA_EXECUTION_ROLE \
                --handler lambda_function.lambda_handler \
                --zip-file fileb://lambda.zip
            fi
          done

      - name: Deploy Flask Frontend to S3
        env:
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
        run: aws s3 sync frontend/ s3://$S3_BUCKET_NAME --delete

      - name: Create Elastic Beanstalk Application
        run: |
          eb init student-app --platform python-3.8 --region ${{ secrets.AWS_REGION }}
          if ! eb status student-env 2>/dev/null; then
            eb create student-env --instance-types t2.micro
          else
            eb deploy student-env
          fi

      - name: Get Application URL
        id: get_url
        run: |
          APP_URL=$(aws elasticbeanstalk describe-environments \
            --environment-names student-env \
            --query "Environments[0].CNAME" \
            --output text)
          echo "Application URL: http://$APP_URL"
          echo "app_url=http://$APP_URL" >> $GITHUB_OUTPUT

      - name: Create Status File
        run: |
          echo "# Deployment Status" > deployment_status.md
          echo "Flask App URL: http://${{ steps.get_url.outputs.app_url }}" >> deployment_status.md
          echo "Lambda Add Student API: ${{ env.ADD_STUDENT_URL }}" >> deployment_status.md
          echo "Lambda Get Students API: ${{ env.GET_STUDENTS_URL }}" >> deployment_status.md

      - name: Upload Status as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: deployment-status
          path: deployment_status.md
          retention-days: 5

      - name: Invalidate CloudFront Cache (Optional)
        if: env.CLOUDFRONT_DISTRIBUTION_ID != ''
        env:
          CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
        run: |
          aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*" || echo "Skipping CloudFront invalidation"
